/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FileReference {
  'id' : string,
  'file' : ExternalBlob,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
}
export interface FileReferenceInput {
  'id' : string,
  'file' : ExternalBlob,
  'name' : string,
}
export interface Product {
  'isForWomen' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'isForMen' : boolean,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'imageUrl' : string,
  'clothingType' : string,
  'brand' : string,
  'price' : number,
  'isForKids' : boolean,
  'availableColours' : Array<string>,
}
export interface ProductFilter {
  'isForWomen' : [] | [boolean],
  'isForMen' : [] | [boolean],
  'maxPrice' : [] | [number],
  'clothingType' : [] | [string],
  'brand' : [] | [string],
  'minPrice' : [] | [number],
  'isForKids' : [] | [boolean],
}
export interface ProductInput {
  'isForWomen' : boolean,
  'name' : string,
  'isForMen' : boolean,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'imageUrl' : string,
  'clothingType' : string,
  'brand' : string,
  'price' : number,
  'isForKids' : boolean,
  'availableColours' : Array<string>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFileReference' : ActorMethod<[FileReferenceInput], FileReference>,
  'createProduct' : ActorMethod<[ProductInput], undefined>,
  'deleteFileReference' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllFileReferences' : ActorMethod<[], Array<FileReference>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileReference' : ActorMethod<[string], [] | [FileReference]>,
  'getFilteredProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFileReference' : ActorMethod<
    [string, FileReferenceInput],
    FileReference
  >,
  'updateProduct' : ActorMethod<[bigint, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];