/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileReferenceInput = IDL.Record({
  'id' : IDL.Text,
  'file' : ExternalBlob,
  'name' : IDL.Text,
});
export const FileReference = IDL.Record({
  'id' : IDL.Text,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
});
export const ProductInput = IDL.Record({
  'isForWomen' : IDL.Bool,
  'name' : IDL.Text,
  'isForMen' : IDL.Bool,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'clothingType' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Float64,
  'isForKids' : IDL.Bool,
  'availableColours' : IDL.Vec(IDL.Text),
});
export const Product = IDL.Record({
  'isForWomen' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isForMen' : IDL.Bool,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'clothingType' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Float64,
  'isForKids' : IDL.Bool,
  'availableColours' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ProductFilter = IDL.Record({
  'isForWomen' : IDL.Opt(IDL.Bool),
  'isForMen' : IDL.Opt(IDL.Bool),
  'maxPrice' : IDL.Opt(IDL.Float64),
  'clothingType' : IDL.Opt(IDL.Text),
  'brand' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Float64),
  'isForKids' : IDL.Opt(IDL.Bool),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFileReference' : IDL.Func([FileReferenceInput], [FileReference], []),
  'createProduct' : IDL.Func([ProductInput], [], []),
  'deleteFileReference' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFileReference' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FileReference)],
      ['query'],
    ),
  'getFilteredProducts' : IDL.Func(
      [ProductFilter],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFileReference' : IDL.Func(
      [IDL.Text, FileReferenceInput],
      [FileReference],
      [],
    ),
  'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileReferenceInput = IDL.Record({
    'id' : IDL.Text,
    'file' : ExternalBlob,
    'name' : IDL.Text,
  });
  const FileReference = IDL.Record({
    'id' : IDL.Text,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
  });
  const ProductInput = IDL.Record({
    'isForWomen' : IDL.Bool,
    'name' : IDL.Text,
    'isForMen' : IDL.Bool,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'clothingType' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Float64,
    'isForKids' : IDL.Bool,
    'availableColours' : IDL.Vec(IDL.Text),
  });
  const Product = IDL.Record({
    'isForWomen' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isForMen' : IDL.Bool,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'clothingType' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Float64,
    'isForKids' : IDL.Bool,
    'availableColours' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ProductFilter = IDL.Record({
    'isForWomen' : IDL.Opt(IDL.Bool),
    'isForMen' : IDL.Opt(IDL.Bool),
    'maxPrice' : IDL.Opt(IDL.Float64),
    'clothingType' : IDL.Opt(IDL.Text),
    'brand' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Float64),
    'isForKids' : IDL.Opt(IDL.Bool),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFileReference' : IDL.Func([FileReferenceInput], [FileReference], []),
    'createProduct' : IDL.Func([ProductInput], [], []),
    'deleteFileReference' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFileReference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FileReference)],
        ['query'],
      ),
    'getFilteredProducts' : IDL.Func(
        [ProductFilter],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFileReference' : IDL.Func(
        [IDL.Text, FileReferenceInput],
        [FileReference],
        [],
      ),
    'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };